---
title: Peyote
author: Peyote
email: attila@peyote.network
description: Peyote is working to create the next-generation of debt derivatives on
  the blockchain.
baseurl: "/ubuild-jekyll"
url: peyote.network
defaults: []
plugins:
- jekyll-feed
- jekyll-menus
