---
title: Peyote
author: Peyote
email: attila@peyote.network
description: Peyote is working to create the next-generation of debt derivatives on
  the blockchain.
baseurl: "/ubuild-jekyll"
url: peyote.network
defaults:
- scope:
    path: page
  values:
    layout: color
plugins:
- jekyll-feed
- jekyll-menus
